"""empty message

Revision ID: 04d4e2d7df48
Revises: ac93207527db
Create Date: 2025-07-08 14:12:50.515810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04d4e2d7df48'
down_revision = 'ac93207527db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('update_time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_user', schema=None) as batch_op:
        batch_op.drop_column('update_time')
        batch_op.drop_column('create_time')

    # ### end Alembic commands ###
