"""empty message

Revision ID: 2bcdc489a3ce
Revises: 1d22b38b5494
Create Date: 2025-07-10 11:41:45.988289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bcdc489a3ce'
down_revision = '1d22b38b5494'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_roles_menus',
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('menu_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['menu_id'], ['t_menu.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['t_role.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_roles_menus')
    # ### end Alembic commands ###
